USE [OptikIT]
GO

INSERT INTO [dbo].[CUSTOMERS]
           ([CS_STAMP]
           ,[CS_CUSTNO]
           ,[CS_CREATIONDATE]
           ,[CS_CPRNO]
           ,[CS_FIRSTNAME]
           ,[CS_LASTNAME]
           ,[CS_ADRESS1]
           ,[CS_ADRESS2]
           ,[CS_ZIPCODE]
           ,[CS_COUNTYNO]
           ,[CS_PHONEPRIVATE]
           ,[CS_PHONEPRIVATEEXT]
           ,[CS_PHONEPRIVATEAVAIL]
           ,[CS_PHONEWORK]
           ,[CS_PHONEWORKEXT]
           ,[CS_PHONEWORKAVAIL]
           ,[CS_PHONEMOBILE]
           ,[CS_PHONEMOBILEEXT]
           ,[CS_PHONEMOBILEAVAIL]
           ,[CS_FAX]
           ,[CS_FAXEXT]
           ,[CS_AVAILABLEATA]
           ,[CS_OCCUPATION]
           ,[CS_HOBBY]
           ,[CS_EMAIL]
           ,[CS_EMAILCOMMERCIALS]
           ,[CS_RECEIVEMAIL]
           ,[CS_TILTULATION]
           ,[CS_GENDER]
           ,[CS_SUBDANMARK]
           ,[CS_SUB58]
           ,[CS_SUBPENSIONER]
           ,[CS_LEGALGUARDIANCPR]
           ,[CS_LEGALGUARDIANFIRSTNAME]
           ,[CS_LEGALGUARDIANLASTNAME]
           ,[CS_LEGALGUARDIANPHONE]
           ,[CS_SUB97]
           ,[CS_MAILCOMMERCIALS]
           ,[CS_PAYMENTCONDITION]
           ,[CS_RABAT]
           ,[CS_CUSTGROUP]
           ,[CS_OWNOPTICIAN]
           ,[CS_OJENLAEGE]
           ,[CS_TLFOPFDATO]
           ,[CS_TLFOPFBEM]
           ,[CS_KOMMUNENAVN]
           ,[CS_PBSSTATUS]
           ,[CS_PBSCPRNR]
           ,[CS_PBSREGNR]
           ,[CS_PBSKONTONR]
           ,[CS_PBSAFTALENR]
           ,[CS_PBSMAX]
           ,[CS_PBSMIN]
           ,[CS_PBSDATE]
           ,[CS_USER]
           ,[CS_LASTGLASSES]
           ,[CS_LASTLENS]
           ,[CS_MODTAGER]
           ,[CS_MODFIRST]
           ,[CS_MODLAST]
           ,[CS_MODADRESSE]
           ,[CS_MODZIPCODE]
           ,[CS_MODCOUNTRY]
           ,[CS_RECIEVEEMAIL]
           ,[CS_OLDPBSCUSTNO]
           ,[CS_MODEANCODE]
           ,[CS_PBSLINE1]
           ,[CS_PBSLINE2]
           ,[CS_WEB_USERNAME]
           ,[CS_BALANCE]
           ,[CS_PBSCOUNTRY]
           ,[CS_COMMERCIALS_SMS]
           ,[CS_COMMERCIALS_EMAIL]
           ,[CS_COMMERCIALS_LETTER]
           ,[CS_DEBTORTYPE]
           ,[CS_OLDMODTAGERNO]
           ,[CS_WEBSITE]
           ,[CS_EANCODE]
           ,[CS_FORCED_REFNO]
           ,[CS_ACTIVE]
           ,[CS_CANEDIT]
           ,[CS_VATCODES]
           ,[CS_PAYINFO]
           ,[CS_ATT]
           ,[CS_CUSTOMERDEBTOR]
           ,[CS_BONUSCARD]
           ,[CS_BONUSCARD_REF]
           ,[CS_BIRTHDAY])
     VALUES
			(1,
			1,
			 1998-12-08,
			  120612-4245,
			  'Andreas', 
			  'Edelmann',
			  'Bakkesvinget 2',
			  'Bakkesvinget 3',
			  2010,
			  2,
			  '23425342',
			  'hejs',
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  23525867,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  'bruger@gmail.com',
			  NULL,
			  1,
			  NULL,
			  1,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  1,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  1995-12-08
			    )

				INSERT INTO [dbo].[CUSTOMERS]
           ([CS_STAMP]
           ,[CS_CUSTNO]
           ,[CS_CREATIONDATE]
           ,[CS_CPRNO]
           ,[CS_FIRSTNAME]
           ,[CS_LASTNAME]
           ,[CS_ADRESS1]
           ,[CS_ADRESS2]
           ,[CS_ZIPCODE]
           ,[CS_COUNTYNO]
           ,[CS_PHONEPRIVATE]
           ,[CS_PHONEPRIVATEEXT]
           ,[CS_PHONEPRIVATEAVAIL]
           ,[CS_PHONEWORK]
           ,[CS_PHONEWORKEXT]
           ,[CS_PHONEWORKAVAIL]
           ,[CS_PHONEMOBILE]
           ,[CS_PHONEMOBILEEXT]
           ,[CS_PHONEMOBILEAVAIL]
           ,[CS_FAX]
           ,[CS_FAXEXT]
           ,[CS_AVAILABLEATA]
           ,[CS_OCCUPATION]
           ,[CS_HOBBY]
           ,[CS_EMAIL]
           ,[CS_EMAILCOMMERCIALS]
           ,[CS_RECEIVEMAIL]
           ,[CS_TILTULATION]
           ,[CS_GENDER]
           ,[CS_SUBDANMARK]
           ,[CS_SUB58]
           ,[CS_SUBPENSIONER]
           ,[CS_LEGALGUARDIANCPR]
           ,[CS_LEGALGUARDIANFIRSTNAME]
           ,[CS_LEGALGUARDIANLASTNAME]
           ,[CS_LEGALGUARDIANPHONE]
           ,[CS_SUB97]
           ,[CS_MAILCOMMERCIALS]
           ,[CS_PAYMENTCONDITION]
           ,[CS_RABAT]
           ,[CS_CUSTGROUP]
           ,[CS_OWNOPTICIAN]
           ,[CS_OJENLAEGE]
           ,[CS_TLFOPFDATO]
           ,[CS_TLFOPFBEM]
           ,[CS_KOMMUNENAVN]
           ,[CS_PBSSTATUS]
           ,[CS_PBSCPRNR]
           ,[CS_PBSREGNR]
           ,[CS_PBSKONTONR]
           ,[CS_PBSAFTALENR]
           ,[CS_PBSMAX]
           ,[CS_PBSMIN]
           ,[CS_PBSDATE]
           ,[CS_USER]
           ,[CS_LASTGLASSES]
           ,[CS_LASTLENS]
           ,[CS_MODTAGER]
           ,[CS_MODFIRST]
           ,[CS_MODLAST]
           ,[CS_MODADRESSE]
           ,[CS_MODZIPCODE]
           ,[CS_MODCOUNTRY]
           ,[CS_RECIEVEEMAIL]
           ,[CS_OLDPBSCUSTNO]
           ,[CS_MODEANCODE]
           ,[CS_PBSLINE1]
           ,[CS_PBSLINE2]
           ,[CS_WEB_USERNAME]
           ,[CS_BALANCE]
           ,[CS_PBSCOUNTRY]
           ,[CS_COMMERCIALS_SMS]
           ,[CS_COMMERCIALS_EMAIL]
           ,[CS_COMMERCIALS_LETTER]
           ,[CS_DEBTORTYPE]
           ,[CS_OLDMODTAGERNO]
           ,[CS_WEBSITE]
           ,[CS_EANCODE]
           ,[CS_FORCED_REFNO]
           ,[CS_ACTIVE]
           ,[CS_CANEDIT]
           ,[CS_VATCODES]
           ,[CS_PAYINFO]
           ,[CS_ATT]
           ,[CS_CUSTOMERDEBTOR]
           ,[CS_BONUSCARD]
           ,[CS_BONUSCARD_REF]
           ,[CS_BIRTHDAY])

			VALUES	
			
			(1,
			1,
			 1995-11-05,
			  120285-4245,
			  'Andre', 
			  'Edel',
			  'Bakkes 2',
			  'Bakkes 3',
			  2008,
			  3,
			  '23425245',
			  'davs',
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  23524867,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  'bruger1@gmail.com',
			  NULL,
			  2,
			  NULL,
			  2,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  2,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  1993-12-08
			    )

								INSERT INTO [dbo].[CUSTOMERS]
           ([CS_STAMP]
           ,[CS_CUSTNO]
           ,[CS_CREATIONDATE]
           ,[CS_CPRNO]
           ,[CS_FIRSTNAME]
           ,[CS_LASTNAME]
           ,[CS_ADRESS1]
           ,[CS_ADRESS2]
           ,[CS_ZIPCODE]
           ,[CS_COUNTYNO]
           ,[CS_PHONEPRIVATE]
           ,[CS_PHONEPRIVATEEXT]
           ,[CS_PHONEPRIVATEAVAIL]
           ,[CS_PHONEWORK]
           ,[CS_PHONEWORKEXT]
           ,[CS_PHONEWORKAVAIL]
           ,[CS_PHONEMOBILE]
           ,[CS_PHONEMOBILEEXT]
           ,[CS_PHONEMOBILEAVAIL]
           ,[CS_FAX]
           ,[CS_FAXEXT]
           ,[CS_AVAILABLEATA]
           ,[CS_OCCUPATION]
           ,[CS_HOBBY]
           ,[CS_EMAIL]
           ,[CS_EMAILCOMMERCIALS]
           ,[CS_RECEIVEMAIL]
           ,[CS_TILTULATION]
           ,[CS_GENDER]
           ,[CS_SUBDANMARK]
           ,[CS_SUB58]
           ,[CS_SUBPENSIONER]
           ,[CS_LEGALGUARDIANCPR]
           ,[CS_LEGALGUARDIANFIRSTNAME]
           ,[CS_LEGALGUARDIANLASTNAME]
           ,[CS_LEGALGUARDIANPHONE]
           ,[CS_SUB97]
           ,[CS_MAILCOMMERCIALS]
           ,[CS_PAYMENTCONDITION]
           ,[CS_RABAT]
           ,[CS_CUSTGROUP]
           ,[CS_OWNOPTICIAN]
           ,[CS_OJENLAEGE]
           ,[CS_TLFOPFDATO]
           ,[CS_TLFOPFBEM]
           ,[CS_KOMMUNENAVN]
           ,[CS_PBSSTATUS]
           ,[CS_PBSCPRNR]
           ,[CS_PBSREGNR]
           ,[CS_PBSKONTONR]
           ,[CS_PBSAFTALENR]
           ,[CS_PBSMAX]
           ,[CS_PBSMIN]
           ,[CS_PBSDATE]
           ,[CS_USER]
           ,[CS_LASTGLASSES]
           ,[CS_LASTLENS]
           ,[CS_MODTAGER]
           ,[CS_MODFIRST]
           ,[CS_MODLAST]
           ,[CS_MODADRESSE]
           ,[CS_MODZIPCODE]
           ,[CS_MODCOUNTRY]
           ,[CS_RECIEVEEMAIL]
           ,[CS_OLDPBSCUSTNO]
           ,[CS_MODEANCODE]
           ,[CS_PBSLINE1]
           ,[CS_PBSLINE2]
           ,[CS_WEB_USERNAME]
           ,[CS_BALANCE]
           ,[CS_PBSCOUNTRY]
           ,[CS_COMMERCIALS_SMS]
           ,[CS_COMMERCIALS_EMAIL]
           ,[CS_COMMERCIALS_LETTER]
           ,[CS_DEBTORTYPE]
           ,[CS_OLDMODTAGERNO]
           ,[CS_WEBSITE]
           ,[CS_EANCODE]
           ,[CS_FORCED_REFNO]
           ,[CS_ACTIVE]
           ,[CS_CANEDIT]
           ,[CS_VATCODES]
           ,[CS_PAYINFO]
           ,[CS_ATT]
           ,[CS_CUSTOMERDEBTOR]
           ,[CS_BONUSCARD]
           ,[CS_BONUSCARD_REF]
           ,[CS_BIRTHDAY])

			VALUES	
			
			(1,
			1,
			 1993-10-06,
			  100212-3245,
			  'Danny', 
			  'Nielsen',
			  'Baks 2',
			  'Baks 3',
			  2005,
			  4,
			  '54425245',
			  'test',
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  23524885,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  'bruger2@gmail.com',
			  NULL,
			  2,
			  NULL,
			  3,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  3,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  1991-05-08
			    )

								INSERT INTO [dbo].[CUSTOMERS]
           ([CS_STAMP]
           ,[CS_CUSTNO]
           ,[CS_CREATIONDATE]
           ,[CS_CPRNO]
           ,[CS_FIRSTNAME]
           ,[CS_LASTNAME]
           ,[CS_ADRESS1]
           ,[CS_ADRESS2]
           ,[CS_ZIPCODE]
           ,[CS_COUNTYNO]
           ,[CS_PHONEPRIVATE]
           ,[CS_PHONEPRIVATEEXT]
           ,[CS_PHONEPRIVATEAVAIL]
           ,[CS_PHONEWORK]
           ,[CS_PHONEWORKEXT]
           ,[CS_PHONEWORKAVAIL]
           ,[CS_PHONEMOBILE]
           ,[CS_PHONEMOBILEEXT]
           ,[CS_PHONEMOBILEAVAIL]
           ,[CS_FAX]
           ,[CS_FAXEXT]
           ,[CS_AVAILABLEATA]
           ,[CS_OCCUPATION]
           ,[CS_HOBBY]
           ,[CS_EMAIL]
           ,[CS_EMAILCOMMERCIALS]
           ,[CS_RECEIVEMAIL]
           ,[CS_TILTULATION]
           ,[CS_GENDER]
           ,[CS_SUBDANMARK]
           ,[CS_SUB58]
           ,[CS_SUBPENSIONER]
           ,[CS_LEGALGUARDIANCPR]
           ,[CS_LEGALGUARDIANFIRSTNAME]
           ,[CS_LEGALGUARDIANLASTNAME]
           ,[CS_LEGALGUARDIANPHONE]
           ,[CS_SUB97]
           ,[CS_MAILCOMMERCIALS]
           ,[CS_PAYMENTCONDITION]
           ,[CS_RABAT]
           ,[CS_CUSTGROUP]
           ,[CS_OWNOPTICIAN]
           ,[CS_OJENLAEGE]
           ,[CS_TLFOPFDATO]
           ,[CS_TLFOPFBEM]
           ,[CS_KOMMUNENAVN]
           ,[CS_PBSSTATUS]
           ,[CS_PBSCPRNR]
           ,[CS_PBSREGNR]
           ,[CS_PBSKONTONR]
           ,[CS_PBSAFTALENR]
           ,[CS_PBSMAX]
           ,[CS_PBSMIN]
           ,[CS_PBSDATE]
           ,[CS_USER]
           ,[CS_LASTGLASSES]
           ,[CS_LASTLENS]
           ,[CS_MODTAGER]
           ,[CS_MODFIRST]
           ,[CS_MODLAST]
           ,[CS_MODADRESSE]
           ,[CS_MODZIPCODE]
           ,[CS_MODCOUNTRY]
           ,[CS_RECIEVEEMAIL]
           ,[CS_OLDPBSCUSTNO]
           ,[CS_MODEANCODE]
           ,[CS_PBSLINE1]
           ,[CS_PBSLINE2]
           ,[CS_WEB_USERNAME]
           ,[CS_BALANCE]
           ,[CS_PBSCOUNTRY]
           ,[CS_COMMERCIALS_SMS]
           ,[CS_COMMERCIALS_EMAIL]
           ,[CS_COMMERCIALS_LETTER]
           ,[CS_DEBTORTYPE]
           ,[CS_OLDMODTAGERNO]
           ,[CS_WEBSITE]
           ,[CS_EANCODE]
           ,[CS_FORCED_REFNO]
           ,[CS_ACTIVE]
           ,[CS_CANEDIT]
           ,[CS_VATCODES]
           ,[CS_PAYINFO]
           ,[CS_ATT]
           ,[CS_CUSTOMERDEBTOR]
           ,[CS_BONUSCARD]
           ,[CS_BONUSCARD_REF]
           ,[CS_BIRTHDAY])

			VALUES	
			
			(1,
			1,
			 1991-9-05,
			  120888-4345,
			  'Andre', 
			  'Edel',
			  'Bakkes 2',
			  'Bakkes 3',
			  2008,
			  3,
			  '23425245',
			  'davs',
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  23524867,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  'bruger3@gmail.com',
			  NULL,
			  2,
			  NULL,
			  3,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  3,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  1990-10-04
			    )

										INSERT INTO [dbo].[CUSTOMERS]
           ([CS_STAMP]
           ,[CS_CUSTNO]
           ,[CS_CREATIONDATE]
           ,[CS_CPRNO]
           ,[CS_FIRSTNAME]
           ,[CS_LASTNAME]
           ,[CS_ADRESS1]
           ,[CS_ADRESS2]
           ,[CS_ZIPCODE]
           ,[CS_COUNTYNO]
           ,[CS_PHONEPRIVATE]
           ,[CS_PHONEPRIVATEEXT]
           ,[CS_PHONEPRIVATEAVAIL]
           ,[CS_PHONEWORK]
           ,[CS_PHONEWORKEXT]
           ,[CS_PHONEWORKAVAIL]
           ,[CS_PHONEMOBILE]
           ,[CS_PHONEMOBILEEXT]
           ,[CS_PHONEMOBILEAVAIL]
           ,[CS_FAX]
           ,[CS_FAXEXT]
           ,[CS_AVAILABLEATA]
           ,[CS_OCCUPATION]
           ,[CS_HOBBY]
           ,[CS_EMAIL]
           ,[CS_EMAILCOMMERCIALS]
           ,[CS_RECEIVEMAIL]
           ,[CS_TILTULATION]
           ,[CS_GENDER]
           ,[CS_SUBDANMARK]
           ,[CS_SUB58]
           ,[CS_SUBPENSIONER]
           ,[CS_LEGALGUARDIANCPR]
           ,[CS_LEGALGUARDIANFIRSTNAME]
           ,[CS_LEGALGUARDIANLASTNAME]
           ,[CS_LEGALGUARDIANPHONE]
           ,[CS_SUB97]
           ,[CS_MAILCOMMERCIALS]
           ,[CS_PAYMENTCONDITION]
           ,[CS_RABAT]
           ,[CS_CUSTGROUP]
           ,[CS_OWNOPTICIAN]
           ,[CS_OJENLAEGE]
           ,[CS_TLFOPFDATO]
           ,[CS_TLFOPFBEM]
           ,[CS_KOMMUNENAVN]
           ,[CS_PBSSTATUS]
           ,[CS_PBSCPRNR]
           ,[CS_PBSREGNR]
           ,[CS_PBSKONTONR]
           ,[CS_PBSAFTALENR]
           ,[CS_PBSMAX]
           ,[CS_PBSMIN]
           ,[CS_PBSDATE]
           ,[CS_USER]
           ,[CS_LASTGLASSES]
           ,[CS_LASTLENS]
           ,[CS_MODTAGER]
           ,[CS_MODFIRST]
           ,[CS_MODLAST]
           ,[CS_MODADRESSE]
           ,[CS_MODZIPCODE]
           ,[CS_MODCOUNTRY]
           ,[CS_RECIEVEEMAIL]
           ,[CS_OLDPBSCUSTNO]
           ,[CS_MODEANCODE]
           ,[CS_PBSLINE1]
           ,[CS_PBSLINE2]
           ,[CS_WEB_USERNAME]
           ,[CS_BALANCE]
           ,[CS_PBSCOUNTRY]
           ,[CS_COMMERCIALS_SMS]
           ,[CS_COMMERCIALS_EMAIL]
           ,[CS_COMMERCIALS_LETTER]
           ,[CS_DEBTORTYPE]
           ,[CS_OLDMODTAGERNO]
           ,[CS_WEBSITE]
           ,[CS_EANCODE]
           ,[CS_FORCED_REFNO]
           ,[CS_ACTIVE]
           ,[CS_CANEDIT]
           ,[CS_VATCODES]
           ,[CS_PAYINFO]
           ,[CS_ATT]
           ,[CS_CUSTOMERDEBTOR]
           ,[CS_BONUSCARD]
           ,[CS_BONUSCARD_REF]
           ,[CS_BIRTHDAY])

			VALUES	
			
			(1,
			1,
			 1990-04-05,
			  120577-4345,
			  'Daniel', 
			  'Edel',
			  'Bakkes 2',
			  'Bakkes 3',
			  20013,
			  4,
			  '23425245',
			  'davs',
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  23524867,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  'bruger4@gmail.com',
			  NULL,
			  1,
			  NULL,
			  4,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  4,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  1989-07-04
			    )

														INSERT INTO [dbo].[CUSTOMERS]
           ([CS_STAMP]
           ,[CS_CUSTNO]
           ,[CS_CREATIONDATE]
           ,[CS_CPRNO]
           ,[CS_FIRSTNAME]
           ,[CS_LASTNAME]
           ,[CS_ADRESS1]
           ,[CS_ADRESS2]
           ,[CS_ZIPCODE]
           ,[CS_COUNTYNO]
           ,[CS_PHONEPRIVATE]
           ,[CS_PHONEPRIVATEEXT]
           ,[CS_PHONEPRIVATEAVAIL]
           ,[CS_PHONEWORK]
           ,[CS_PHONEWORKEXT]
           ,[CS_PHONEWORKAVAIL]
           ,[CS_PHONEMOBILE]
           ,[CS_PHONEMOBILEEXT]
           ,[CS_PHONEMOBILEAVAIL]
           ,[CS_FAX]
           ,[CS_FAXEXT]
           ,[CS_AVAILABLEATA]
           ,[CS_OCCUPATION]
           ,[CS_HOBBY]
           ,[CS_EMAIL]
           ,[CS_EMAILCOMMERCIALS]
           ,[CS_RECEIVEMAIL]
           ,[CS_TILTULATION]
           ,[CS_GENDER]
           ,[CS_SUBDANMARK]
           ,[CS_SUB58]
           ,[CS_SUBPENSIONER]
           ,[CS_LEGALGUARDIANCPR]
           ,[CS_LEGALGUARDIANFIRSTNAME]
           ,[CS_LEGALGUARDIANLASTNAME]
           ,[CS_LEGALGUARDIANPHONE]
           ,[CS_SUB97]
           ,[CS_MAILCOMMERCIALS]
           ,[CS_PAYMENTCONDITION]
           ,[CS_RABAT]
           ,[CS_CUSTGROUP]
           ,[CS_OWNOPTICIAN]
           ,[CS_OJENLAEGE]
           ,[CS_TLFOPFDATO]
           ,[CS_TLFOPFBEM]
           ,[CS_KOMMUNENAVN]
           ,[CS_PBSSTATUS]
           ,[CS_PBSCPRNR]
           ,[CS_PBSREGNR]
           ,[CS_PBSKONTONR]
           ,[CS_PBSAFTALENR]
           ,[CS_PBSMAX]
           ,[CS_PBSMIN]
           ,[CS_PBSDATE]
           ,[CS_USER]
           ,[CS_LASTGLASSES]
           ,[CS_LASTLENS]
           ,[CS_MODTAGER]
           ,[CS_MODFIRST]
           ,[CS_MODLAST]
           ,[CS_MODADRESSE]
           ,[CS_MODZIPCODE]
           ,[CS_MODCOUNTRY]
           ,[CS_RECIEVEEMAIL]
           ,[CS_OLDPBSCUSTNO]
           ,[CS_MODEANCODE]
           ,[CS_PBSLINE1]
           ,[CS_PBSLINE2]
           ,[CS_WEB_USERNAME]
           ,[CS_BALANCE]
           ,[CS_PBSCOUNTRY]
           ,[CS_COMMERCIALS_SMS]
           ,[CS_COMMERCIALS_EMAIL]
           ,[CS_COMMERCIALS_LETTER]
           ,[CS_DEBTORTYPE]
           ,[CS_OLDMODTAGERNO]
           ,[CS_WEBSITE]
           ,[CS_EANCODE]
           ,[CS_FORCED_REFNO]
           ,[CS_ACTIVE]
           ,[CS_CANEDIT]
           ,[CS_VATCODES]
           ,[CS_PAYINFO]
           ,[CS_ATT]
           ,[CS_CUSTOMERDEBTOR]
           ,[CS_BONUSCARD]
           ,[CS_BONUSCARD_REF]
           ,[CS_BIRTHDAY])

			VALUES	
			
			(1,
			1,
			 1978-04-05,
			  120977-4345,
			  'Daniel P', 
			  'Ed',
			  'Bakes 2',
			  'Bakes 3',
			  20013,
			  4,
			  '80425245',
			  'davs',
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  22524867,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  'bruger5@gmail.com',
			  NULL,
			  1,
			  NULL,
			  5,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  5,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  NULL,
			  1984-01-09
			    )